/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterEditor: typeof import('./src/components/CharacterEditor.vue')['default']
    CharacterSelector: typeof import('./src/components/CharacterSelector.vue')['default']
    CharacterSettings: typeof import('./src/components/settings/tabs/CharacterSettings.vue')['default']
    GazeSettings: typeof import('./src/components/settings/tabs/GazeSettings.vue')['default']
    OpenAISettings: typeof import('./src/components/settings/tabs/OpenAISettings.vue')['default']
    RecordingSettings: typeof import('./src/components/settings/tabs/RecordingSettings.vue')['default']
    RoastSettings: typeof import('./src/components/settings/tabs/RoastSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/settings/SettingsPanel.vue')['default']
    SimpleLive2DViewer: typeof import('./src/components/SimpleLive2DViewer.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_00f9f0d9ed8ce3fed9054c7fe6f18b7b/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  }
}
