/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterEditor: typeof import('./src/components/CharacterEditor.vue')['default']
    CharacterSelector: typeof import('./src/components/CharacterSelector.vue')['default']
    CharacterSettings: typeof import('./src/components/settings/tabs/CharacterSettings.vue')['default']
    GazeSettings: typeof import('./src/components/settings/tabs/GazeSettings.vue')['default']
    OpenAISettings: typeof import('./src/components/settings/tabs/OpenAISettings.vue')['default']
    RoastSettings: typeof import('./src/components/settings/tabs/RoastSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/settings/SettingsPanel.vue')['default']
    SimpleLive2DViewer: typeof import('./src/components/SimpleLive2DViewer.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_c72f20f133428a31fb746f02b8ae0ee4/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
